import { ILikes } from './likes.interface';
import { IUser } from './user.interface';

export interface IPost {
  _id: string;
  // userId: string;
  user: IUser;
  image: string;
  caption: string;
  likes: ILikes[];
  comments: string[];
  cratedAt: Date;
  updatedAt: Date;
}

// Generated by https://quicktype.io

export interface PostsResponse {
  posts: Post[];
}

export interface Post {
  _id: string;
  user: User;
  image: string;
  caption: string;
  likes: Like[];
  comments: any[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Like {
  _id: string;
  user: User;
  post: string;
  __v: number;
}

export interface User {
  _id: string;
  name: string;
  email: string;
  image: string;
  emailVerified: null;
}
// Generated by https://quicktype.io

export interface PostByID {
  post: Post;
}
