// Generated by https://quicktype.io

export interface UsersResponse {
  users: User[];
}

export interface User {
  _id: string;
  name: string;
  email: string;
  image: string;
  emailVerified: null;
}

// Generated by https://quicktype.io

export interface UserByIDResponse {
  user: User;
}
